# Generated by Django 3.1.1 on 2020-10-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Your_locker', '0003_auto_20201008_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
