# Generated by Django 3.1.1 on 2020-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Your_locker', '0004_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('home_title', models.CharField(max_length=250)),
                ('upload', models.CharField(max_length=1000)),
            ],
        ),
    ]
